# Generated by Django 3.2 on 2021-04-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_rename_whatsapp_whatsappmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsappModel',
        ),
    ]
